replicaCount : 1
image :
repository : mongo
tag : latest
pullPolicy : IfNotPresent
service:
  host: mongodb-service  # The name of your MongoDB service
  port: 27017           # The default MongoDB port
  type : ClusterIP
ingress :
enabled : false

