replicaCount: 1

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  host: mongodb-service
  port: 27017
  type: ClusterIP

ingress:
  enabled: false
  annotations: {}
  className: ""
  hosts:
    - host: mongodb.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

serviceAccount:
  create: true
  name: mongodb-service-account

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
