replicaCount: 1

image:
  repository: azizbouassida11/gestion-parc-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

serviceAccount:
  create: true
  name: ""

env:
  - name: MONGO_URI
    value: mongodb://mongodb:27017/mern-app
  - name: PORT
    value: "5000"

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: backend.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
