replicaCount: 3

image:
  repository: your-frontend-image
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

serviceAccount:
  create: true

env:
  - name: REACT_APP_SERVER_URL
    value: "http://server:5000"

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: mern-app.local
      paths:  
        - path: /
          pathType: Prefix

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
